name: tests

on:
  pull_request:
    branches:
      - master
      - devel

jobs:
  tests:
    name: tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup python version
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
          architecture: x64
      - name: Restore cached deps
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
      - name: Install application and deps
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Linting
        run: |
          pip install flake8
          flake8 .
      - name: Run tests
        run: |
          pip install pytest requests six
          pytest
